AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for s3 bucket     
Resources:
  UgoBucket:
    Type: AWS::S3::Bucket    
    Properties:
      BucketName: basefirst-2

Outputs:
  BucketName:
    Description: Name of bucket
    Value: !Ref UgoBucket
    Export:
      Name: NetBucket
  BucketARN:
    Description: Arn of bucket
    Value: !GetAtt
      - UgoBucket
      - Arn
    Export:
      Name: NetBucketArn