AWSTemplateFormatVersion: '2010-09-09'
Description: "Ec2 instances template"

Parameters:
  Environment:
    Description: "Application environment"
    Type: String
    Default: development
    AllowedValues:
      - development
      - testing
      - acceptance
      - production

  AMIID:
    Description: "Ec2 Image Id"
    Type: String
    Default: "ami-00c39f71452c08778"
  InstanceType:
    Description: "Type of Ec2 instance"
    Default: "t2.micro"
    Type: String

Conditions:
  CreateOnlyOnProduction: !Equals
    - !Ref Environment
    - "production"

Resources:
  webserver:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMIID
      InstanceType: !Ref InstanceType
      BlockDeviceMappings: 
      - DeviceName: "/dev/xvda"
        Ebs: 
          VolumeType: "io1"
          Iops: "200"
          DeleteOnTermination: true
          VolumeSize: "8"

  S3Bucket:
    Type: AWS::S3::Bucket
    Condition: CreateOnlyOnProduction